/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.extension.example.jooq;


import com.epam.reportportal.extension.example.jooq.tables.JEntity;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JExample extends SchemaImpl {

    private static final long serialVersionUID = 1666768148;

    /**
     * The reference instance of <code>example</code>
     */
    public static final JExample EXAMPLE = new JExample();

    /**
     * The table <code>example.entity</code>.
     */
    public final JEntity ENTITY = com.epam.reportportal.extension.example.jooq.tables.JEntity.ENTITY;

    /**
     * No further instances allowed
     */
    private JExample() {
        super("example", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ENTITY_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            JEntity.ENTITY);
    }
}
