/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.extension.example.jooq;


import com.epam.reportportal.extension.example.jooq.tables.JEntity;

import javax.annotation.processing.Generated;

import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>example</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<Record, Long> IDENTITY_ENTITY = Identities0.IDENTITY_ENTITY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> ENTITY_PKEY = UniqueKeys0.ENTITY_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<Record, Long> IDENTITY_ENTITY = Internal.createIdentity(JEntity.ENTITY, JEntity.ENTITY.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<Record> ENTITY_PKEY = Internal.createUniqueKey(JEntity.ENTITY, "entity_pkey", JEntity.ENTITY.ID);
    }
}
