/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.extension.example.jooq;


import com.epam.reportportal.extension.example.jooq.tables.JEntity;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in example
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>example.entity</code>.
     */
    public static final JEntity ENTITY = JEntity.ENTITY;
}
