/*
 * WorkItemTracking
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.epam.reportportal.extension.azure.rest.client.model.workitem;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "The JSON model for a JSON Patch")
public class JsonPatchOperation {
  @SerializedName("from")
  private String from = null;

  @SerializedName("op")
  private Object op = null;

  @SerializedName("path")
  private String path = null;

  @SerializedName("value")
  private Object value = null;

  public JsonPatchOperation() {
  }

  public JsonPatchOperation(String from, Object op, String path, Object value) {
    this.from = from;
    this.op = op;
    this.path = path;
    this.value = value;
  }

  public JsonPatchOperation from(String from) {
    this.from = from;
    return this;
  }

  @Schema(description = "The path to copy from for the Move/Copy operation.")
  public String getFrom() {
    return from;
  }

  public void setFrom(String from) {
    this.from = from;
  }

  public JsonPatchOperation op(Object op) {
    this.op = op;
    return this;
  }

  @Schema(description = "The patch operation")
  public Object getOp() {
    return op;
  }

  public void setOp(Object op) {
    this.op = op;
  }

  public JsonPatchOperation path(String path) {
    this.path = path;
    return this;
  }

  @Schema(description = "The path for the operation. In the case of an array, a zero based index can be used to specify the position in the array (e.g. /biscuits/0/name). The \"-\" character can be used instead of an index to insert at the end of the array (e.g. /biscuits/-).")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public JsonPatchOperation value(Object value) {
    this.value = value;
    return this;
  }

  @Schema(description = "The value for the operation. This is either a primitive or a JToken.")
  public Object getValue() {
    return value;
  }

  public void setValue(Object value) {
    this.value = value;
  }

  // ... rest of the class ...
}