/*
 * WorkItemTracking
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.epam.reportportal.extension.azure.rest.client.model.workitem;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;

/**
 * Work item type state name, color and state category
 */
@Schema(description = "Work item type state name, color and state category")
@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-03T21:33:08.123Z")
public class WorkItemStateColor {
  @SerializedName("category")
  private String category = null;

  @SerializedName("color")
  private String color = null;

  @SerializedName("name")
  private String name = null;

  public WorkItemStateColor category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Category of state
   * @return category
  **/
  @Schema(description = "Category of state")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public WorkItemStateColor color(String color) {
    this.color = color;
    return this;
  }

   /**
   * Color value
   * @return color
  **/
  @Schema(description = "Color value")
  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }

  public WorkItemStateColor name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Work item type state name
   * @return name
  **/
  @Schema(description = "Work item type state name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkItemStateColor workItemStateColor = (WorkItemStateColor) o;
    return Objects.equals(this.category, workItemStateColor.category) &&
        Objects.equals(this.color, workItemStateColor.color) &&
        Objects.equals(this.name, workItemStateColor.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(category, color, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkItemStateColor {\n");
    
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
