/*
 * WorkItemTracking
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.epam.reportportal.extension.azure.rest.client.model.workitem;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;

/**
 * Reference to a field in a work item
 */
@Schema(description = "Reference to a field in a work item")
@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-03T21:33:08.123Z")
public class WorkItemFieldReference {
  @SerializedName("name")
  private String name = null;

  @SerializedName("referenceName")
  private String referenceName = null;

  @SerializedName("url")
  private String url = null;

  public WorkItemFieldReference name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The friendly name of the field.
   * @return name
  **/
  @Schema(description = "The friendly name of the field.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public WorkItemFieldReference referenceName(String referenceName) {
    this.referenceName = referenceName;
    return this;
  }

   /**
   * The reference name of the field.
   * @return referenceName
  **/
  @Schema(description = "The reference name of the field.")
  public String getReferenceName() {
    return referenceName;
  }

  public void setReferenceName(String referenceName) {
    this.referenceName = referenceName;
  }

  public WorkItemFieldReference url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The REST URL of the resource.
   * @return url
  **/
  @Schema(description = "The REST URL of the resource.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkItemFieldReference workItemFieldReference = (WorkItemFieldReference) o;
    return Objects.equals(this.name, workItemFieldReference.name) &&
        Objects.equals(this.referenceName, workItemFieldReference.referenceName) &&
        Objects.equals(this.url, workItemFieldReference.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, referenceName, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkItemFieldReference {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    referenceName: ").append(toIndentedString(referenceName)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
