/*
 * WorkItemTracking
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.epam.reportportal.extension.azure.rest.client.model.workitem;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Field Instance of a workItemype with detailed references.
 */
@Schema(description = "Field Instance of a workItemype with detailed references.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-03T21:33:08.123Z")
public class WorkItemTypeFieldWithReferences extends WorkItemTypeFieldInstanceBase {
  @SerializedName("allowedValues")
  private List<Object> allowedValues = null;

  @SerializedName("defaultValue")
  private Object defaultValue = null;

  public WorkItemTypeFieldWithReferences allowedValues(List<Object> allowedValues) {
    this.allowedValues = allowedValues;
    return this;
  }

  public WorkItemTypeFieldWithReferences addAllowedValuesItem(Object allowedValuesItem) {
    if (this.allowedValues == null) {
      this.allowedValues = new ArrayList<Object>();
    }
    this.allowedValues.add(allowedValuesItem);
    return this;
  }

  /**
   * The list of field allowed values.
   *
   * @return allowedValues
   **/
  @Schema(description = "The list of field allowed values.")
  public List<Object> getAllowedValues() {
    return allowedValues;
  }

  public void setAllowedValues(List<Object> allowedValues) {
    this.allowedValues = allowedValues;
  }

  public WorkItemTypeFieldWithReferences defaultValue(Object defaultValue) {
    this.defaultValue = defaultValue;
    return this;
  }

  /**
   * Represents the default value of the field.
   *
   * @return defaultValue
   **/
  @Schema(description = "Represents the default value of the field.")
  public Object getDefaultValue() {
    return defaultValue;
  }

  public void setDefaultValue(Object defaultValue) {
    this.defaultValue = defaultValue;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkItemTypeFieldWithReferences workItemTypeFieldWithReferences =
        (WorkItemTypeFieldWithReferences) o;
    return Objects.equals(this.allowedValues, workItemTypeFieldWithReferences.allowedValues)
        && Objects.equals(this.defaultValue, workItemTypeFieldWithReferences.defaultValue)
        && super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowedValues, defaultValue, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkItemTypeFieldWithReferences {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    allowedValues: ").append(toIndentedString(allowedValues)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
