/*
 * WorkItemTracking
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.epam.reportportal.extension.azure.rest.client.model.workitem;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;

/**
 * Reference to a work item icon.
 */
@Schema(description = "Reference to a work item icon.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-03T21:33:08.123Z")
public class WorkItemIcon {
  @SerializedName("id")
  private String id = null;

  @SerializedName("url")
  private String url = null;

  public WorkItemIcon id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The identifier of the icon.
   * @return id
  **/
  @Schema(description = "The identifier of the icon.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public WorkItemIcon url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The REST URL of the resource.
   * @return url
  **/
  @Schema(description = "The REST URL of the resource.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkItemIcon workItemIcon = (WorkItemIcon) o;
    return Objects.equals(this.id, workItemIcon.id) &&
        Objects.equals(this.url, workItemIcon.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkItemIcon {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
