/*
 * Core
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.epam.reportportal.extension.azure.rest.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * The class to represent a collection of REST reference links.
 */
@Schema(description = "The class to represent a collection of REST reference links.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-07-22T22:33:25.592Z")
public class ReferenceLinks {
  @SerializedName("links")
  private Map<String, Object> links = null;

  public ReferenceLinks links(Map<String, Object> links) {
    this.links = links;
    return this;
  }

  public ReferenceLinks putLinksItem(String key, Object linksItem) {
    if (this.links == null) {
      this.links = new HashMap<String, Object>();
    }
    this.links.put(key, linksItem);
    return this;
  }

   /**
   * The readonly view of the links.  Because Reference links are readonly, we only want to expose them as read only.
   * @return links
  **/
  @Schema(description = "The readonly view of the links.  Because Reference links are readonly, we only want to expose them as read only.")
  public Map<String, Object> getLinks() {
    return links;
  }

  public void setLinks(Map<String, Object> links) {
    this.links = links;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReferenceLinks referenceLinks = (ReferenceLinks) o;
    return Objects.equals(this.links, referenceLinks.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReferenceLinks {\n");
    
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
