/*
 * Core
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.epam.reportportal.extension.azure.rest.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * Represents a shallow reference to a TeamProject.
 */
@Schema(description = "Represents a shallow reference to a TeamProject.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-07-22T22:33:25.592Z")
public class TeamProjectReference {
  @SerializedName("abbreviation")
  private String abbreviation = null;

  @SerializedName("defaultTeamImageUrl")
  private String defaultTeamImageUrl = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("lastUpdateTime")
  private OffsetDateTime lastUpdateTime = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("revision")
  private Long revision = null;

  @SerializedName("state")
  private Object state = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("visibility")
  private Object visibility = null;

  public TeamProjectReference abbreviation(String abbreviation) {
    this.abbreviation = abbreviation;
    return this;
  }

   /**
   * Project abbreviation.
   * @return abbreviation
  **/
  @Schema(description = "Project abbreviation.")
  public String getAbbreviation() {
    return abbreviation;
  }

  public void setAbbreviation(String abbreviation) {
    this.abbreviation = abbreviation;
  }

  public TeamProjectReference defaultTeamImageUrl(String defaultTeamImageUrl) {
    this.defaultTeamImageUrl = defaultTeamImageUrl;
    return this;
  }

   /**
   * Url to default team identity image.
   * @return defaultTeamImageUrl
  **/
  @Schema(description = "Url to default team identity image.")
  public String getDefaultTeamImageUrl() {
    return defaultTeamImageUrl;
  }

  public void setDefaultTeamImageUrl(String defaultTeamImageUrl) {
    this.defaultTeamImageUrl = defaultTeamImageUrl;
  }

  public TeamProjectReference description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The project&#39;s description (if any).
   * @return description
  **/
  @Schema(description = "The project's description (if any).")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TeamProjectReference id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Project identifier.
   * @return id
  **/
  @Schema(description = "Project identifier.")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public TeamProjectReference lastUpdateTime(OffsetDateTime lastUpdateTime) {
    this.lastUpdateTime = lastUpdateTime;
    return this;
  }

   /**
   * Project last update time.
   * @return lastUpdateTime
  **/
  @Schema(description = "Project last update time.")
  public OffsetDateTime getLastUpdateTime() {
    return lastUpdateTime;
  }

  public void setLastUpdateTime(OffsetDateTime lastUpdateTime) {
    this.lastUpdateTime = lastUpdateTime;
  }

  public TeamProjectReference name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Project name.
   * @return name
  **/
  @Schema(description = "Project name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TeamProjectReference revision(Long revision) {
    this.revision = revision;
    return this;
  }

   /**
   * Project revision.
   * @return revision
  **/
  @Schema(description = "Project revision.")
  public Long getRevision() {
    return revision;
  }

  public void setRevision(Long revision) {
    this.revision = revision;
  }

  public TeamProjectReference state(Object state) {
    this.state = state;
    return this;
  }

   /**
   * Project state.
   * @return state
  **/
  @Schema(description = "Project state.")
  public Object getState() {
    return state;
  }

  public void setState(Object state) {
    this.state = state;
  }

  public TeamProjectReference url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Url to the full version of the object.
   * @return url
  **/
  @Schema(description = "Url to the full version of the object.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public TeamProjectReference visibility(Object visibility) {
    this.visibility = visibility;
    return this;
  }

   /**
   * Project visibility.
   * @return visibility
  **/
  @Schema(description = "Project visibility.")
  public Object getVisibility() {
    return visibility;
  }

  public void setVisibility(Object visibility) {
    this.visibility = visibility;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TeamProjectReference teamProjectReference = (TeamProjectReference) o;
    return Objects.equals(this.abbreviation, teamProjectReference.abbreviation) &&
        Objects.equals(this.defaultTeamImageUrl, teamProjectReference.defaultTeamImageUrl) &&
        Objects.equals(this.description, teamProjectReference.description) &&
        Objects.equals(this.id, teamProjectReference.id) &&
        Objects.equals(this.lastUpdateTime, teamProjectReference.lastUpdateTime) &&
        Objects.equals(this.name, teamProjectReference.name) &&
        Objects.equals(this.revision, teamProjectReference.revision) &&
        Objects.equals(this.state, teamProjectReference.state) &&
        Objects.equals(this.url, teamProjectReference.url) &&
        Objects.equals(this.visibility, teamProjectReference.visibility);
  }

  @Override
  public int hashCode() {
    return Objects.hash(abbreviation, defaultTeamImageUrl, description, id, lastUpdateTime, name, revision, state, url, visibility);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TeamProjectReference {\n");
    
    sb.append("    abbreviation: ").append(toIndentedString(abbreviation)).append("\n");
    sb.append("    defaultTeamImageUrl: ").append(toIndentedString(defaultTeamImageUrl)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastUpdateTime: ").append(toIndentedString(lastUpdateTime)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
