/*
 * Core
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.epam.reportportal.extension.azure.rest.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;
import java.util.UUID;

/**
 * 
 */
@Schema(description = "")
@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-07-22T22:33:25.592Z")
public class WebApiTeamRef {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("url")
  private String url = null;

  public WebApiTeamRef id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Team (Identity) Guid. A Team Foundation ID.
   * @return id
  **/
  @Schema(description = "Team (Identity) Guid. A Team Foundation ID.")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public WebApiTeamRef name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Team name
   * @return name
  **/
  @Schema(description = "Team name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public WebApiTeamRef url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Team REST API Url
   * @return url
  **/
  @Schema(description = "Team REST API Url")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebApiTeamRef webApiTeamRef = (WebApiTeamRef) o;
    return Objects.equals(this.id, webApiTeamRef.id) &&
        Objects.equals(this.name, webApiTeamRef.name) &&
        Objects.equals(this.url, webApiTeamRef.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebApiTeamRef {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
